******************************************************************************

               Student Name(s) : Raul Terra Ferrao

               Hand In Time    : Wed Oct 25 22:11:16 2017


******************************************************************************



**************   COMPILATION MESSAGES   **************

make: *** No rule to make target '/home/raul/osp/cpu1.intel/osp.o', needed by 'OSP'.  Pare.


************   COMPILATION MESSAGES END   ************

